<?php

return [
    //'en' => ['name' => 'English', 'order' => 1, 'direction' => 'ltr'],
    'ar' => ['name' => 'Arabic', 'order' => 2, 'direction' => 'rtl'],
    'fr' => ['name' => 'French', 'order' => 3, 'direction' => 'ltr'],
    'de' => ['name' => 'German', 'order' => 4, 'direction' => 'ltr'],
    'zh' => ['name' => 'Chinese', 'order' => 5, 'direction' => 'ltr'],
    'ru' => ['name' => 'Russian', 'order' => 6, 'direction' => 'ltr'],
    'es' => ['name' => 'Spanish', 'order' => 7, 'direction' => 'ltr'],
    'pt' => ['name' => 'Portuguese', 'order' => 8, 'direction' => 'ltr'],
    'it' => ['name' => 'Italian', 'order' => 9, 'direction' => 'ltr'],
    'ja' => ['name' => 'Japanese', 'order' => 10, 'direction' => 'ltr'],
    'ko' => ['name' => 'Korean', 'order' => 11, 'direction' => 'ltr'],
    'pl' => ['name' => 'Polish', 'order' => 12, 'direction' => 'ltr'],
    'sv' => ['name' => 'Swedish', 'order' => 13, 'direction' => 'ltr'],
    'nl' => ['name' => 'Dutch', 'order' => 14, 'direction' => 'ltr'],
    'th' => ['name' => 'Thai', 'order' => 15, 'direction' => 'ltr'],
    'id' => ['name' => 'Indonesian', 'order' => 16, 'direction' => 'ltr'],
    'vn' => ['name' => 'Vietnamese', 'order' => 17, 'direction' => 'ltr'],
    'fi' => ['name' => 'Finnish', 'order' => 18, 'direction' => 'ltr'],
    'bd' => ['name' => 'Bengali', 'order' => 19, 'direction' => 'ltr'],
    'hi' => ['name' => 'Hindi', 'order' => 20, 'direction' => 'ltr'],
    'sw' => ['name' => 'Swahili', 'order' => 21, 'direction' => 'ltr'],
    'sr' => ['name' => 'Serbian', 'order' => 22, 'direction' => 'ltr'],
    'no' => ['name' => 'Norwegian', 'order' => 23, 'direction' => 'ltr'],
    'da' => ['name' => 'Danish', 'order' => 24, 'direction' => 'ltr'],
    'cs' => ['name' => 'Czech', 'order' => 25, 'direction' => 'ltr'],
    'hu' => ['name' => 'Hungarian', 'order' => 26, 'direction' => 'ltr'],
    'ro' => ['name' => 'Romanian', 'order' => 27, 'direction' => 'ltr'],
    'sq' => ['name' => 'Albanian', 'order' => 28, 'direction' => 'ltr'],
    'ie' => ['name' => 'Ireland', 'order' => 29, 'direction' => 'ltr'],
    'uk' => ['name' => 'Ukrainian', 'order' => 30, 'direction' => 'ltr'],
    'fa' => ['name' => 'Persian', 'order' => 31, 'direction' => 'rtl'],
    'el' => ['name' => 'Greek', 'order' => 32, 'direction' => 'ltr'],
    'tr' => ['name' => 'Turkish', 'order' => 33, 'direction' => 'ltr'],
    'af' => ['name' => 'Afrikaans', 'order' => 34, 'direction' => 'ltr'],
];